services:
  - type: web
    name: tech-store-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///data.db"
      - key: JWT_SECRET_KEY
        value: "super-secret-key"
